[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 64
depth = 128
fail_on_revert = true
show_metrics = true

[profile.historical]
test = "fork-test"
